name: ardknob
version: 1.0.0
description: Libraries for hardware radio stacks with Arduino, Dart, and FlighGear flight simulator.
author: John McDole <john@mcdole.org>
homepage: https://github.com/jtmcdole/ardknob
dependencies:
  serial_port: ">=0.3.1 < 0.4.0"
  xml: ">=2.4.1 < 3.0.0"
  logging: ">= 0.11.2 < 1.0.0"
dev_dependencies:
  ansicolor: "^0.0.9"
  ccompile: "^0.2.10"
  coverage: "^0.7.2"
  mockito: "^0.11.0"
  path: "^1.3.9"
  quiver: "^0.21.4"
  test: "^0.12.6+2"
